# Generated by Django 2.2.7 on 2019-11-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=200)),
                ('b_floor', models.CharField(max_length=200)),
                ('b_distance', models.CharField(max_length=200)),
                ('b_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='menuinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=200)),
                ('m_price', models.CharField(max_length=200)),
                ('m_info', models.CharField(max_length=200)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.building')),
            ],
        ),
    ]
